#!/usr/bin/with-contenv sh

set -u # Treat unset variables as an error.

SRVCMD="/usr/bin/wineserver --foreground --persistent"

echo "[$(basename "$(pwd)")] starting..."
if [ "${SUP_GROUP_IDS:-UNSET}" != "UNSET" ]; then
    exec 2>&1 s6-applyuidgid -u $USER_ID -g $GROUP_ID -G $SUP_GROUP_IDS $SRVCMD
else
    exec 2>&1 s6-setuidgid $USER_ID:$GROUP_ID $SRVCMD
fi

# vim: set ft=sh :
